# !---------------------------------------------------------!
# ! File automatically updated at 26.10.2016 13:27:25
# ! to plugin version v5.3.8
# !---------------------------------------------------------!
# ! Unfortunatelly due to how Bukkit handles YAML
# ! configurations, all comments (#) were wiped. 
# ! For reference values and comments visit
# ! https://github.com/kangarko/chatcontrol
# !---------------------------------------------------------!

Anti_Bot:
  Rejoin_Delay_Seconds: 0
  Block_Actions_Until_Moved:
    Chat: false
Anti_Caps:
  Enabled: false
  Warn_Player: false
  Ignore_Usernames: false
  Min_Message_Length: 5
  Min_Caps_Percentage: 50
  Min_Caps_In_A_Row: 5
  Whitelist:
  - OMG
  - LOL
  - WTF
  - WOW
  - ROFL
Anti_Spam:
  Similarity_Check:
    Ignore_Special_Characters: true
    Ignore_Duplicate_Characters: false
    Ignore_First_Arguments_In_Commands: true
  Commands:
    Delay_Between_Commands: 0
    Similar_Percentage_Block: 0
    Whitelist_Delay:
    - spawn
    - home
    Whitelist_Similarity:
    - tell
    - pm
    - t
    - w
    - r
  Chat:
    Delay_Between_Messages: 0
    Similar_Percentage_Block: 50
    Regex_In_Whitelist: false
    Whitelist_Similarity:
    - hello
    - hey
    Whitelist_Delay:
    - true
Chat:
  Formatter:
    Enabled: false
    Message_Format: '%pl_prefix%player:%pl_suffix %message'
    Global_Message_Format: '&8[GLOBAL]&f %pl_prefix%player:%pl_suffix %message'
    Spy_Message_Format: '&8SPY: [%world&8]&f %pl_prefix%player:%pl_suffix %message'
    Ranged_Mode: false
    Range: 100.0
  Grammar:
    Insert_Dot:
      Enabled: false
      Min_Message_Length: 5
    Capitalize:
      Enabled: false
      Min_Message_Length: 5
Clear:
  Broadcast: true
  Do_Not_Clear_For_Staff: true
  Console_Lines_To_Clear: 300
Messages:
  Join: default
  Quit: default
  Kick: default
  Show_Quit_Only_When_Logged: false
  Timed:
    Enabled: false
    Random_Order: false
    Random_No_Repeat: false
    Prefix: '&8[&2Tip&8]&2'
    Suffix: ''
    Delay_Seconds: 180
    Message_List:
      global:
      - Hey, %player, did you know that this server is running ChatControl?
      - 'Visit developer website: &ahttps://goo.gl/CT3Zdl'
      hardcore:
      - Grief is not permitted what-so-ever and every griefer will be banned.
      - Can you survive the night on %world world?
      hardcore_nether:
      - includeFrom hardcore
      ignored-world:
      - excludeGlobal
      creative:
      - excludeGlobal
      - Welcome on Creative world. Enjoy your gamemode :)
Mute:
  Broadcast: true
  Silence:
    Join_Messages: true
    Quit_Messages: true
    Kick_Messages: true
    Death_Messages: true
  Disabled_Commands_During_Mute:
  - me
  - tell
  - msg
  - r
  - w
Packets:
  Enabled: false
  Tab_Complete:
    Disable: true
    Disable_Only_In_Commands: true
    Allow_When_Message_Has_Space: true
    Allow_When_Length_Above: 0
Rules:
  Check_Chat: true
  Check_Commands: true
  Check_Signs: true
  Check_Packets: true
  Packets:
    Deserialize_Json: true
Console:
  Filter:
    Enabled: false
    Filter_Console_Messages:
    - Reached end of stream for
    - Connection reset
    - lost connection
Signs:
  Duplication:
    Deny_Signs_With_Same_Text: false
    Alert_Staff: true
    Block_When_Violates_A_Rule: true
    Drop_Sign: true
Sound_Notify:
  Enabled: true
  Notify_Only_When_Afk: true
  Notify_Only_If_Prefixed_With: '@'
  Sound: ENTITY_CHICKEN_EGG, 1F, 1.5F
  Enabled_In_Commands:
  - msg
  - tell
  - t
  - w
  - r
Groups:
  Enabled: false
  Always_Check_Updates: false
  Group_List:
    trusted:
      Message_Delay: 0
    guest:
      Message_Delay: 4
      Command_Delay: 6
    vip:
      Join_Message: '&6[VIP] &e%player has joined the game'
      Leave_Message: '&6[VIP] &e%player has left the game'
      Kick_Message: none
Updater:
  Enabled: true
  Notify: true
  Download: true
  Check_Notes: true
Writer:
  Write_Chat_Communication: true
  Strip_Colors: true
  Ignore_Players:
  - ignoredAdmin
  Write_Commands:
  - tell
Minimum_Players_To_Enable_Checks: 0
Op_Has_Permissions: true
Regex_Timeout_Milis: 100
Locale: en
Log_Lag_Over_Milis: 100
Verbose_Rules: true
Silent_Startup: true
Reset_Cache_On_Quit: false
Enforce_New_Line: false
Debug: false
Version: 4
